package demiurge.cli

import java.nio.file.Path
import scala.sys.process._

// Phase C: Git integration utilities for branch creation, push, and PR opening.
// Used by build and run commands with --branch and --open-pr flags.
object GitIntegration {

  /** Create a git branch from the worktree HEAD and make it visible in the main repo. */
  def createBranch(repoPath: Path, worktreePath: Path, branchName: String): Either[String, Unit] = {
    try {
      // Get the commit SHA from the worktree
      val sha = Process(List("git", "rev-parse", "HEAD"), worktreePath.toFile).!!.trim
      // Create branch in the main repo pointing at that SHA
      val exitCode = Process(List("git", "branch", branchName, sha), repoPath.toFile).!
      if (exitCode == 0) Right(())
      else Left(s"git branch failed with exit code $exitCode")
    } catch {
      case e: Exception => Left(s"Failed to create branch: ${e.getMessage}")
    }
  }

  /** Push a branch to a remote. */
  def pushBranch(repoPath: Path, branchName: String, remote: String = "origin"): Either[String, Unit] = {
    try {
      val exitCode = Process(List("git", "push", remote, branchName), repoPath.toFile).!
      if (exitCode == 0) Right(())
      else Left(s"git push failed with exit code $exitCode")
    } catch {
      case e: Exception => Left(s"Failed to push branch: ${e.getMessage}")
    }
  }

  /**
   * Open a pull request via GitHub CLI (gh).
   * Returns the PR URL on success.
   */
  def openPullRequest(
    repoPath: Path,
    branchName: String,
    title: String,
    body: String,
    baseBranch: Option[String] = None,
  ): Either[String, String] = {
    // Check if gh is available
    try {
      Process(List("gh", "--version")).!!
    } catch {
      case _: Exception =>
        return Left("GitHub CLI (gh) not found. Install it from https://cli.github.com/ or create the PR manually.")
    }

    try {
      val baseArgs = List("gh", "pr", "create",
        "--head", branchName,
        "--title", title,
        "--body", body,
      )
      val args = baseBranch match {
        case Some(base) => baseArgs ++ List("--base", base)
        case None => baseArgs
      }
      val output = Process(args, repoPath.toFile).!!.trim
      Right(output)
    } catch {
      case e: Exception => Left(s"Failed to open PR: ${e.getMessage}")
    }
  }

  /**
   * Generate a branch name from a task string.
   * Format: demiurge/<slugified-task>-<short-hash>
   */
  def generateBranchName(taskText: String): String = {
    val slug = taskText.toLowerCase
      .replaceAll("[^a-z0-9\\s-]", "")
      .replaceAll("\\s+", "-")
      .take(40)
      .stripSuffix("-")
    val hash = taskText.hashCode.toHexString.take(8)
    s"demiurge/$slug-$hash"
  }

  /**
   * Handle post-run git operations based on --branch and --open-pr flags.
   * Returns a status message describing what was done.
   */
  def handlePostRun(
    repoPath: Path,
    worktreePath: Path,
    taskText: String,
    branch: Option[String],
    openPr: Boolean,
  ): Option[String] = {
    if (branch.isEmpty && !openPr) return None

    val branchName = branch.getOrElse(generateBranchName(taskText))

    // Step 1: Create branch
    createBranch(repoPath, worktreePath, branchName) match {
      case Left(err) => return Some(s"Warning: Could not create branch: $err")
      case Right(_) =>
    }

    if (!openPr) {
      return Some(s"Branch created: $branchName\n  To switch: git checkout $branchName")
    }

    // Step 2: Push branch
    pushBranch(repoPath, branchName) match {
      case Left(err) => return Some(s"Branch created: $branchName\n  Warning: Could not push: $err")
      case Right(_) =>
    }

    // Step 3: Open PR
    val prTitle = taskText.take(72)
    val prBody = s"## Demiurge Build\n\nTask: $taskText\n\nBranch: `$branchName`\n\nGenerated by `demiurge build`."

    openPullRequest(repoPath, branchName, prTitle, prBody) match {
      case Right(url) => Some(s"PR opened: $url\n  Branch: $branchName")
      case Left(err) => Some(s"Branch pushed: $branchName\n  Warning: Could not open PR: $err")
    }
  }
}
