load("@rules_scala//scala:scala.bzl", "scala_junit_test", "scala_library")

scala_library(
    name = "requirements",
    srcs = glob(["src/main/scala/**/*.scala"]),
    visibility = ["//visibility:public"],
    deps = [
        "@maven//:org_yaml_snakeyaml",
    ],
)

scala_junit_test(
    name = "requirements-tests",
    srcs = glob(["src/test/scala/**/*.scala"], allow_empty = True),
    suffixes = ["Suite"],
    deps = [
        ":requirements",
        "@maven//:org_yaml_snakeyaml",
        "@maven//:org_scalameta_munit_2_13",
        "@maven//:org_scalameta_munit_diff_2_13",
    ],
)
