package demiurge.config

import demiurge.model._

// Phase A: Writes ResolvedConfig back to YAML format for caching in .demiurge/inferred/
object InferredConfigWriter {

  def toManifestYaml(config: ResolvedConfig): String = {
    val sb = new StringBuilder
    sb.append("# Auto-generated by demiurge — do not edit manually\n")
    sb.append("# Override by placing a demiurge.yaml in your repo root\n")
    sb.append("version: 1\n\n")

    // app
    sb.append("app:\n")
    sb.append(s"  type: ${config.app.appType}\n")
    sb.append(s"  root_url: ${config.app.rootUrl}\n")
    config.app.apiUrl.foreach(u => sb.append(s"  api_url: $u\n"))

    // services
    if (config.services.nonEmpty) {
      sb.append("\nservices:\n")
      config.services.foreach { svc =>
        sb.append(s"  ${svc.serviceId}:\n")
        sb.append(s"    kind: ${svc.kind}\n")
        sb.append(s"    startup_mode: ${svc.startupMode}\n")
        svc.startupCommand.foreach(c => sb.append(s"    startup_command: $c\n"))
        svc.composeTarget.foreach(t => sb.append(s"    compose_target: $t\n"))
        svc.cwd.foreach(c => sb.append(s"    cwd: $c\n"))
        if (svc.ports.nonEmpty) {
          sb.append("    ports:\n")
          svc.ports.foreach { p =>
            sb.append(s"      - container: ${p.container}\n")
            p.host.foreach(h => sb.append(s"        host: $h\n"))
          }
        }
        if (svc.dependsOn.nonEmpty) {
          sb.append("    depends_on:\n")
          svc.dependsOn.foreach(d => sb.append(s"      - $d\n"))
        }
        svc.readiness.foreach { r =>
          sb.append("    readiness:\n")
          sb.append(s"      probe_type: ${r.probeType}\n")
          sb.append(s"      target: ${r.target}\n")
          sb.append(s"      interval_ms: ${r.intervalMs}\n")
          sb.append(s"      timeout_ms: ${r.timeoutMs}\n")
          sb.append(s"      max_failures: ${r.maxFailures}\n")
        }
        sb.append(s"    required: ${svc.required}\n")
      }
    }

    // fixtures
    config.fixtures.foreach { f =>
      sb.append("\nfixtures:\n")
      val strategyStr = f.resetStrategy match {
        case ResetStrategy.SoftReset => "soft"
        case ResetStrategy.HardReset => "hard"
        case ResetStrategy.FullRebuild => "full_rebuild"
      }
      sb.append(s"  reset_strategy: $strategyStr\n")
      if (f.seedSteps.nonEmpty) {
        sb.append("  seed_steps:\n")
        f.seedSteps.foreach { s =>
          sb.append(s"    - step_id: ${s.stepId}\n")
          sb.append(s"      command: ${s.command}\n")
          s.cwd.foreach(c => sb.append(s"      cwd: $c\n"))
          sb.append(s"      timeout_ms: ${s.timeoutMs}\n")
          if (s.runOnInitOnly) sb.append("      run_on_init_only: true\n")
          if (s.runOnReset) sb.append("      run_on_reset: true\n")
        }
      }
    }

    // auth
    config.auth.foreach { a =>
      sb.append("\nauth:\n")
      val modeStr = a.mode match {
        case AuthMode.BrowserFormLogin => "browser_form_login"
        case AuthMode.ApiLogin => "api_login"
        case AuthMode.StaticTestToken => "static_test_token"
        case AuthMode.SeededLocalSession => "seeded_local_session"
        case AuthMode.DevBypassHeader => "dev_bypass_header"
      }
      sb.append(s"  mode: $modeStr\n")
      a.loginUrl.foreach(u => sb.append(s"  login_url: $u\n"))
      if (a.credentials.nonEmpty) {
        sb.append("  credentials:\n")
        a.credentials.foreach { case (k, v) => sb.append(s"    $k: $v\n") }
      }
      a.staticToken.foreach(t => sb.append(s"  static_token: $t\n"))
      a.storageStateOutput.foreach(s => sb.append(s"  storage_state_output: $s\n"))
    }

    // verification
    sb.append("\nverification:\n")
    sb.append(s"  default_verifier_timeout_ms: ${config.verification.defaultVerifierTimeoutMs}\n")
    sb.append(s"  default_browser_action_timeout_ms: ${config.verification.defaultBrowserActionTimeoutMs}\n")
    sb.append(s"  max_retries: ${config.verification.maxRetries}\n")
    sb.append(s"  retry_delay_ms: ${config.verification.retryDelayMs}\n")
    sb.append(s"  screenshot_on_failure: ${config.verification.screenshotOnFailure}\n")
    sb.append(s"  screenshot_on_complete: ${config.verification.screenshotOnComplete}\n")
    sb.append(s"  trace_enabled: ${config.verification.traceEnabled}\n")

    // inference
    sb.append("\ninference:\n")
    val providerStr = config.inference.defaultProvider match {
      case InferenceProvider.Anthropic => "anthropic"
      case InferenceProvider.OpenAI => "openai"
      case InferenceProvider.Local => "local"
      case InferenceProvider.Mock => "mock"
    }
    sb.append(s"  default_provider: $providerStr\n")
    if (config.inference.models.nonEmpty) {
      sb.append("  models:\n")
      config.inference.models.foreach { case (k, v) => sb.append(s"    $k: $v\n") }
    }

    // policies
    sb.append("\npolicies:\n")
    sb.append(s"  max_attempts: ${config.policies.maxAttempts}\n")
    sb.append(s"  run_timeout_ms: ${config.policies.runTimeoutMs}\n")
    sb.append(s"  attempt_timeout_ms: ${config.policies.attemptTimeoutMs}\n")
    sb.append(s"  max_patch_lines: ${config.policies.maxPatchLines}\n")
    sb.append(s"  max_artifact_disk_bytes: ${config.policies.maxArtifactDiskBytes}\n")

    sb.toString()
  }
}
