package lastmile.cli.Commands

import java.nio.file.{Files, Path}
import java.sql.Connection

import lastmile.cli._
import lastmile.cli.CommandParsers._

// Phase 7: `lastmile init-manifest` command — Spec §14.1
// Deterministic repo inspection to generate a minimal lastmile.yaml.
// No LLM use. Pragmatic, not magical.
object InitManifestCommand {

  def execute(cmd: InitManifestCmd, global: GlobalOpts, conn: Connection): Int = {
    val outputPath = global.repo.resolve(cmd.output)

    if (Files.exists(outputPath) && !cmd.force) {
      System.err.println(OutputFormatter.formatError(
        s"File already exists: $outputPath (use --force to overwrite)", global.format))
      return ExitCodes.InputError
    }

    val manifest = generateManifest(global.repo)

    Files.createDirectories(outputPath.getParent)
    Files.writeString(outputPath, manifest)

    System.out.println(OutputFormatter.formatSuccess(
      s"Manifest written to $outputPath", global.format))
    ExitCodes.Success
  }

  private def generateManifest(repoPath: Path): String = {
    val hasPackageJson = Files.exists(repoPath.resolve("package.json"))
    val hasDockerCompose = Files.exists(repoPath.resolve("docker-compose.yml")) ||
      Files.exists(repoPath.resolve("docker-compose.yaml")) ||
      Files.exists(repoPath.resolve("compose.yml")) ||
      Files.exists(repoPath.resolve("compose.yaml"))

    val appType = detectAppType(repoPath)
    val rootUrl = "http://localhost:3000"

    val sb = new StringBuilder
    sb.append("# Generated by lastmile init-manifest\n")
    sb.append("version: 1\n\n")
    sb.append("app:\n")
    sb.append(s"  appType: $appType\n")
    sb.append(s"  rootUrl: $rootUrl\n")

    // Detect API URL
    if (appType == "fullstack" || appType == "api") {
      sb.append("  apiUrl: http://localhost:3000/api\n")
    }

    sb.append("\nservices:\n")

    if (hasPackageJson) {
      sb.append("  app:\n")
      sb.append("    kind: Frontend\n")
      sb.append("    startupMode: ScriptNative\n")
      sb.append("    startupCommand: npm start\n")
      sb.append("    ports:\n")
      sb.append("      - container: 3000\n")
      sb.append("    readiness:\n")
      sb.append("      probeType: http\n")
      sb.append("      target: http://localhost:3000\n")
    }

    if (hasDockerCompose) {
      sb.append("  docker-services:\n")
      sb.append("    kind: Api\n")
      sb.append("    startupMode: ComposeNative\n")
    }

    sb.toString()
  }

  private def detectAppType(repoPath: Path): String = {
    val hasPackageJson = Files.exists(repoPath.resolve("package.json"))
    if (!hasPackageJson) return "api"

    try {
      val content = Files.readString(repoPath.resolve("package.json"))
      val hasReact = content.contains("\"react\"")
      val hasNext = content.contains("\"next\"")
      val hasVue = content.contains("\"vue\"")
      val hasAngular = content.contains("\"@angular/core\"")
      val hasExpress = content.contains("\"express\"")
      val hasFastify = content.contains("\"fastify\"")

      if ((hasReact || hasNext || hasVue || hasAngular) && (hasExpress || hasFastify)) "fullstack"
      else if (hasReact || hasNext || hasVue || hasAngular) "frontend"
      else if (hasExpress || hasFastify) "api"
      else "fullstack" // safe default
    } catch {
      case _: Exception => "fullstack"
    }
  }
}
