package demiurge.cli.Commands

import java.nio.file.{Files, Path}
import java.sql.Connection

import demiurge.cli._
import demiurge.cli.CommandParsers._
import demiurge.inspector.RepoInspectorImpl
import demiurge.config.{ConfigResolverImpl, InferredConfigWriter}

// Phase A: `demiurge init` command (also aliased as `init-manifest`).
// Smart repo inspection to generate demiurge.yaml and requirements.yaml.
// Uses deterministic analysis by default; --smart flag enables LLM augmentation.
object InitManifestCommand {

  def execute(cmd: InitManifestCmd, global: GlobalOpts, conn: Connection): Int = {
    val outputPath = global.repo.resolve(cmd.output)

    if (Files.exists(outputPath) && !cmd.force) {
      System.err.println(OutputFormatter.formatError(
        s"File already exists: $outputPath (use --force to overwrite)", global.format))
      return ExitCodes.InputError
    }

    if (!global.quiet) System.err.println("Inspecting repository...")

    // Use ConfigResolver to produce a smart, inferred config
    val runId = s"init-${java.util.UUID.randomUUID().toString.take(8)}"
    val inspection = RepoInspectorImpl.inspect(runId, global.repo, None)

    val resolvedConfig = ConfigResolverImpl.resolve(
      repoPath = global.repo,
      taskText = "Initialize configuration",
      changedFiles = None,
      inspection = inspection,
      inferenceService = None,
    )

    // Generate manifest YAML from the resolved config
    val manifest = InferredConfigWriter.toManifestYaml(resolvedConfig)

    Files.createDirectories(outputPath.getParent)
    Files.writeString(outputPath, manifest)

    if (!global.quiet) {
      System.err.println(s"  Detected: ${inspection.languages.map(_.value).mkString(", ")}")
      System.err.println(s"  Frameworks: ${inspection.frameworks.map(_.value).mkString(", ")}")
      System.err.println(s"  Services: ${resolvedConfig.services.map(_.serviceId).mkString(", ")}")
    }

    // Also generate requirements.yaml with environment readiness checks
    val reqsPath = global.repo.resolve("requirements.yaml")
    if (!Files.exists(reqsPath) || cmd.force) {
      val reqsYaml = generateRequirementsYaml(resolvedConfig)
      if (reqsYaml.nonEmpty) {
        Files.writeString(reqsPath, reqsYaml)
        if (!global.quiet) {
          System.err.println(s"  Requirements written to $reqsPath")
        }
      }
    }

    System.out.println(OutputFormatter.formatSuccess(
      s"Manifest written to $outputPath", global.format))
    ExitCodes.Success
  }

  /** Generate requirements.yaml from resolved config readiness probes. */
  private def generateRequirementsYaml(config: demiurge.model.ResolvedConfig): String = {
    val services = config.services.filter(s => s.required && s.readiness.isDefined)
    if (services.isEmpty) return ""

    val sb = new StringBuilder
    sb.append("# Auto-generated by demiurge init\n")
    sb.append("requirements:\n")

    services.foreach { svc =>
      svc.readiness.foreach { r =>
        val reqType = r.probeType.toLowerCase match {
          case "http" => "http"
          case "tcp" => "tcp"
          case _ => "http"
        }
        sb.append(s"  - id: ${svc.serviceId}-readiness\n")
        sb.append(s"    type: $reqType\n")
        sb.append(s"    description: ${svc.serviceId} is healthy and responding\n")
        sb.append(s"    expected: ${r.target}\n")
        sb.append(s"    timeout_ms: ${r.timeoutMs}\n")
        sb.append(s"    retry: 2\n")
        sb.append(s"    severity: required\n")
      }
    }

    sb.toString()
  }
}
